theme: minima
title: My blog about ansible
author: Angela
email: testaccount@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Right so we're boutta talk bout ansible. Who knows what it is?
  I didn't! It is for automating stuff and is good for devops.
  It uses the yaml syntax (I believe syntax is the correct term).
  Molecule can also be used to test ansible roles!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
